[project]
name = "rock-paper-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "cvzone",
    "gtts",
    "mediapipe==0.10.18",
    "opencv-python",
    "protobuf",
    "pygame",
]

[project.scripts]
rock-paper-ai = "rock_paper_ai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
